app:
  security:
    oauth2:
      clientId: nightfury
      secret: secret
      lifeTime: 600 # 10 minutes
redis:
  config:
    cache:
      host: localhost
      port: 6379
      password: "SevenEightTwo782"
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/learn_microservice?allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: SevenEightTwo782
    driverClassName: com.mysql.cj.jdbc.Driver
server:
  port: 8081